apiVersion: v1
kind: Template
labels:
  template: {{ item[1] }}-jenkins-contra-sample-project-slave-builder
metadata:
  annotations:
    description: Contra Sample Slaves
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: {{ item[1] }}-jenkins-contra-sample-project-slave-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-label: {{ item[1] }}-jenkins-contra-sample-project-slave {{ item[1] }}-jenkins-contra-slave {{ item[1] }}-contra-slave
    labels:
      role: {{ item[1] }}-jenkins-slave
    name: {{ item[1] }}-jenkins-contra-sample-project-slave
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: {{ item[1] }}-jenkins-contra-sample-project-slave
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: {{ item[1] }}-jenkins-contra-sample-project-slave:latest
    resources: {}
    source:
      contextDir: ${CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/CentOS-PaaS-SIG/contra-env-sample-project
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: CONTEXTDIR
  value: config/s2i/jenkins/slave
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
