apiVersion: v1
kind: Template
labels:
  template: rpmbuild-builder
metadata:
  annotations:
    description: rpmbuild container
    iconClass: rpmbuild
    tags: instant-app
  name: rpmbuild-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: rpmbuild
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rpmbuild
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rpmbuild:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: rpmbuild
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/CentOS-PaaS-SIG/ci-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/Dockerfiles/rpmbuild
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
