apiVersion: v1
kind: Template
labels:
  template: cloud-image-compose-builder
metadata:
  annotations:
    description: cloud-image-compose container
    iconClass: cloud-image-compose
    tags: instant-app
  name: cloud-image-compose-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: cloud-image-compose
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: cloud-image-compose
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cloud-image-compose:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: cloud-image-compose
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/CentOS-PaaS-SIG/ci-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/Dockerfiles/cloud-image-compose
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
